--CREATE DATABASE TESTEDB

--USE TESTEDB
--GO

CREATE LOGIN [NOTE\COSTA]  
    FROM WINDOWS  
    WITH DEFAULT_DATABASE = [TESTEDB];  
GO  

CREATE USER [CD] FOR LOGIN [NOTE\CD];  

CREATE TABLE TABLE_TESTE (
    ID INT PRIMARY KEY,
	NOME VARCHAR (30) NOT NULL,
	IDADE INT NOT NULL,
	SALARIO NUMERIC (10, 2) NOT NULL
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE_TESTE TO PUBLIC

SELECT * FROM TABLE_TESTE

INSERT INTO TABLE_TESTE VALUES (1, 'MARCON', 62, 2525.10);
INSERT INTO TABLE_TESTE VALUES (2, 'AUDRON', 22, 352843);
INSERT INTO TABLE_TESTE VALUES (3, 'NILTRON', 31, 161827);
INSERT INTO TABLE_TESTE VALUES (4, 'SEMPRON', 42, 422110);
INSERT INTO TABLE_TESTE VALUES (5, 'FECTRON', 39, 367695);

UPDATE TABLE_TESTE SET SALARIO = 1000.15 WHERE ID = 1 

DROP TABLE TABLE_TESTE

ALTER TABLE TABLE_TESTE ALTER COLUMN SALARIO NUMERIC (10,2)
GO  
SELECT ID, NOME, IDADE, SALARIO, SALARIO * 12 AS SALARIO_ANUAL 
FROM TABLE_TESTE


