CREATE DATABASE DBTESTE

CREATE TABLE 
	CLIENTES 
(
	CLIENTE_ID VARCHAR(255),
	NOME VARCHAR(255),
	NOME_MEIO VARCHAR(255),
	SOBRENOME VARCHAR(255)
)

INSERT INTO CLIENTES VALUES ('1', 'CLOVIS', 'DANIEL', 'MELLO')
INSERT INTO CLIENTES VALUES ('2', 'MARCIANA', 'BELAGGIO', 'COSTEIRA')
INSERT INTO CLIENTES VALUES ('3', 'HELOISA', 'BELAGGIO', 'COSTA')
INSERT INTO CLIENTES VALUES ('4', 'MARIANA', 'APARECIDA', 'COSTEIRA')
INSERT INTO CLIENTES VALUES ('5', 'MARIVONE', 'MORAES', 'BELAGGIO')

SELECT * FROM CLIENTES WHERE SOBRENOME = 'MELLO'

SELECT * FROM CLIENTES WHERE SOBRENOME LIKE 'COS%'

SELECT * FROM CLIENTES

